### ISSUE TITLE
Scraping Policy

### ISSUE THREAD

**Issue by Everlag** [ideocl4st/mtgcoverage-v2-heroku#2]
Being able to scrape mtgcoverage for links to tournament videos would be great. Without an explicit stance on scraping, its difficult to comfortably invest time into programming a scraper.

**Comment by Nightfirecat** [comment]
Scrapers aren't really too hard to code... Realistically, yes, it would be better to provide an API but a basic scraper shouldn't be too much effort to be overly concerned with imo.

**Comment by jaeiclee** [comment]
Sorry about being _very_ late to reply :-/ I didn't get any notification about someone posting in here...

I don't have anything against scraper itself as long as it uses the website's bandwidth reasonably.

However, I do want to ask you what you are going to do with the scraped data.

Since If you are simply going to republish them on another website, it would be nicer to put up a link to MTGCoverage instead. ;)

**Comment by Everlag** [comment]
The idea is to be able to provide a video of an archetype in action beside a sample decklist and some stats. The scraper shouldn't hit MTGCoverage's format pages more than once a day except during development.

I'd be happy to put a notice under the video ala 'video via mtgcoverage.com'.

**Comment by jaeiclee** [comment]
Sounds good to me then! 

Do keep in mind that between the two weeks of my unintended silence, video links in deck pages are now ordered by format and date; so you should be careful when you are dealing with decks that were covered in multiple formats.

**Comment by Everlag** [comment]
Fantastic!

I'm scraping format pages to avoid having to normalize deck names for input, thanks for letting me know though.
